query ListCompanies {
  company {
    business_stage {
      name
    }
    city
    country
    id
    name
    size
    business_objective {
      description
      value
    }
    createdAt
    investmentEtaMetric
    investmentEtaValue
  }
}
