query posts {
  post(order_by: {created_at: desc}) {
    id
    created_at
    content
    companyId
    attachments
    isDeleted
    isPromoted
    user {
      firstname
      lastname
    }
  }
}
