query monthly_growths {
  monthly_growth {
    month
    total
    growth
  }
  monthly_growth_company {
    total
    month
    growth
  }
  monthly_growth_post {
    growth
    month
    total
  }
  monthly_growth_comment {
    growth
    month
    total
  }
  daily_growth {
    day
    total
    growth
  }
  daily_growth_company {
    total
    day
    growth
  }
  daily_growth_post {
    growth
    day
    total
  }
  daily_growth_comment {
    growth
    day
    total
  }
  
  weekly_growth {
    week
    total
    growth
  }
  weekly_growth_company {
    total
    week
    growth
  }
  weekly_growth_post {
    growth
    week
    total
  }
  weekly_growth_comment {
    growth
    week
    total
  }
}
