query monthly_growths {
  monthly_growth {
    month
    total
    growth
  }
  monthly_growth_company {
    total
    month
    growth
  }
  monthly_growth_post {
    growth
    month
    total
  }
  monthly_growth_comment {
    growth
    month
    total
  }
  monthly_active_user {
    growth
    month
    total
  }
  monthly_active_comment_user {
    growth
    month
    total
  }
  monthly_active_post_user {
    growth
    month
    total
  }

  daily_growth {
    day
    total
    growth
  }
  daily_growth_company {
    total
    day
    growth
  }
  daily_growth_post {
    growth
    day
    total
  }
  daily_growth_comment {
    growth
    day
    total
  }
  daily_active_user {
    growth
    day
    total
  }
  daily_active_post_users {
    growth
    day
    total
  }
  daily_active_comment_users {
    growth
    day
    total
  }

  weekly_growth {
    week
    total
    growth
  }
  weekly_growth_company {
    total
    week
    growth
  }
  weekly_growth_post {
    growth
    week
    total
  }
  weekly_growth_comment {
    growth
    week
    total
  }
  weekly_active_user {
    growth
    week
    total
  }
  weekly_active_post_user {
    growth
    week
    total
  }
  weekly_active_comment_user {
    growth
    week
    total
  }
}
