query TOUR_DATA {
  tour(order_by: { stage: asc }) {
    createdAt
    descriptions
    id
    stage
    time
    title
    tour_steps(
      where: { parent: { _is_null: true } }
      order_by: { position: asc }
    ) {
      createdAt
      description
      descriptions
      offset
      params
      route
      target
      time
      title
      tourId
      position
      id
      type
      updatedAt
      tour_steps(order_by: { position: asc }) {
        title
        time
        target
        route
        parent
        offset
        id
        position
        descriptions
        description
        createdAt
      }
    }
  }
}
