query user($id: Int!) {
  user_by_pk(id: $id) {
    email
    firstname
    lastname
    id
    createdAt
    teams {
      company {
        name
        id
      }
    }
    posts_aggregate {
      aggregate {
        count
      }
    }
    comments_aggregate {
      aggregate {
        count
      }
    }
    posts {
      content
      createdAt
       user {
          firstname
          lastname
          profilePhoto
        }
    }
    post_comments_aggregate {
      aggregate {
        count
      }
    }
    post_comments {
      content
        user {
          firstname
          lastname
          profilePhoto
        }
    }
    post_saves_aggregate {
      aggregate {
        count
      }
    }
    post_saves {
      id
      post {
        id
        content
        user {
          firstname
          lastname
          profilePhoto
        }
      }
    }
  }
}
