query Users {
  user(order_by: {firstname: asc_nulls_last, createdAt : desc}) {
    id
    firstname
    email
    lastname
    profilePhoto
    createdAt
    teams {
      id
      company {
        id
        name
      }
    }
  }
}
